title: Python 教學
description: Python 程式設計教學資源
theme: jekyll-theme-primer
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-relative-links
  - jekyll-readme-index
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Python/*.md
